import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { SideBar } from "@/components/SideBar";
import { Provider } from "react-redux";
import store from "@/redux/store";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const monserrat = Montserrat({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-monserrat'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
